#!/bin/sh
# MALHEUR - Automatic Analysis of Malware Behavior
# Copyright (c) 2009 Konrad Rieck (konrad.rieck@tu-berlin.de)
# Berlin Institute of Technology (TU Berlin).
#

ACLOCAL=aclocal
AUTOHEADER=autoheader
AUTOMAKE=automake
AUTOCONF=autoconf
LIBTOOLIZE=libtoolize

rm -f aclocal.m4
rm -f m4/lib* m4/lt*

echo "Autotools"
echo " + aclocal..."     && $ACLOCAL -I m4 && \
echo " + libtoolize..."  && $LIBTOOLIZE --force --copy && \
echo " + autoheader..."  && $AUTOHEADER -f  && \
echo " + automake..."    && $AUTOMAKE --foreign --add-missing --copy && \
echo " + autoconf..."    && $AUTOCONF

echo "Bootstrap complete"
exit
