#!/bin/sh
# MALHEUR - Automatic Malware Analysis on Steroids
# Copyright (c) 2009 Konrad Rieck (rieck@cs.tu-berlin.de)
# Berlin Institute of Technology (TU Berlin).
#

# Get requested configuration
if test -n "$1" ; then
   arg=$1
else
   arg=`hostname`
fi

#make distclean

# Apply configuration
case $arg in
   # Cluster nodes at Fraunhofer FIRST
   bot*|vnc*)
       echo "# Configuration: VNC/Bot"
       PKG_CONFIG_PATH="$HOME/usr/lib/pkgconfig" \
       CC="gcc-4.3" \
       CFLAGS="-fomit-frame-pointer -pedantic -pipe -O3 -march=opteron" \
       ./configure --enable-matlab --with-matlab=/home/matrix/matlab \
                   --prefix=$HOME/usr
       ;;   
   # Cluster nodes at Berlin Institute of Technology        
   node*)
       echo "# Configuration: Node"
       PKG_CONFIG_PATH="$HOME/usr/lib/pkgconfig" \
       CC="gcc" \
       CPPFLAGS="-I $HOME/usr/include" \
       CFLAGS="-fomit-frame-pointer -pedantic -pipe -O3 -march=native" \
       ./configure --enable-matlab -with-matlab=/usr/local/matlab2009a \
                   --prefix=$HOME/usr
       ;;       
   twoface*|rieck*|gwlan*)
       echo "# Configuration: Twoface/Rieck"
       CC="gcc-mp-4.4" \
       CFLAGS="-DDEBUG -g -pedantic -pipe -O2" \
       ./configure --enable-openmp --prefix=/opt/rieck
       ;;
   debug)
       echo "# Configuration: Debug"
       CC="/usr/bin/gcc" \
       CFLAGS="-DDEBUG -ggdb -pedantic" \
       ./configure --prefix=/opt/rieck
       ;;
   *)    
       echo "# Configuration: Standard"
       CFLAGS="-g -pedantic -pipe -O3" \
       ./configure --enable-openmp
       ;;
esac

if test $? -gt 0 ; then
   echo "Error: Configuration failed"
   exit 1
fi

read

# Compile
make clean 
make -j 4 
