#!/bin/sh
# MALHEUR - Automatic Malware Analysis on Steroids
# Copyright (c) 2009 Konrad Rieck (rieck@cs.tu-berlin.de)
# Berlin Institute of Technology (TU Berlin).
#

# Get requested configuration
if test -n "$1" ; then
   arg=$1
else
   arg=`hostname`
fi

make distclean

# Apply configuration
case $arg in
   # Cluster nodes at Fraunhofer FIRST
   bot*|vnc*)
       echo "# Configuration: VNC/Bot"
       PKG_CONFIG_PATH="$HOME/usr/lib/pkgconfig" \
       CC="gcc-4.3" \
       CFLAGS="-fomit-frame-pointer -pedantic -pipe -O3 -march=opteron" \
       ./configure --enable-matlab --with-matlab=/home/matrix/matlab \
                   --prefix=$HOME/usr
       ;;   
   # Cluster nodes at Berlin Institute of Technology        
   node*)
       echo "# Configuration: Node"
       PKG_CONFIG_PATH="$HOME/usr/lib/pkgconfig" \
       CC="gcc" \
       CPPFLAGS="-I $HOME/usr/include" \
       CFLAGS="-fomit-frame-pointer -pedantic -pipe -O3 -march=native" \
       ./configure --enable-openmp \
                   --enable-matlab -with-matlab=/usr/local/matlab2009a \
                   --prefix=$HOME/usr
       ;;       
   # Konrad's laptop    
   twoface*|rieck*|gwlan*)
       echo "# Configuration: Twoface/Rieck"
       CC="/opt/local/bin/gcc-mp-4.3" \
       CFLAGS="-g -pedantic -pipe -O3 -march=nocona" \
       ./configure --enable-matlab -with-matlab=$HOME/Applications/Matlab \
       		   --enable-openmp \
                   --prefix=/opt/malheur
       ;;
   *)    
       echo "# Configuration: Standard"
       CFLAGS="-g -pedantic -pipe -O3" \
       ./configure --enable-openmp
       ;;
esac

if test $? -gt 0 ; then
   echo "Error: Configuration failed"
   exit 1
fi

read

# Compile
make clean 
make -j 4 
