#!/bin/sh
# MALHEUR - Automatic Analysis of Malware Behavior
# Copyright (c) 2009-2012 Konrad Rieck (konrad@mlsec.org)          
# University of Goettingen, Berlin Institute of Technology
#

# Get requested configuration
if test -n "$1" ; then
   arg=$1
else
   arg=`hostname`
fi

# Apply configuration
case $arg in
   # Cluster nodes at Goettingen
   schulle*)
       echo "# Configuration: Schulle"
       CC="gcc" \
       CFLAGS="-fomit-frame-pointer -pedantic -pipe -O3 -march=native" \
       ./configure --enable-openmp
       ;;  
   # My slow laptop      
   scarecrow*|twoface*)
       echo "# Configuration: Twoface/Rieck/GWLan"
       CC="gcc" \
       LDFLAGS="-L/usr/local/opt/libarchive/lib" \
       CPPFLAGS="-I/usr/local/opt/libarchive/include" \
       CFLAGS="-DDEBUG -g -pedantic -pipe -O2" \
       ./configure --prefix=/opt/rieck --enable-openmp
       ;;
   debug)
       echo "# Configuration: Debug"
       CC="/usr/bin/gcc" \
       CFLAGS="-DDEBUG -ggdb -pedantic" \
       ./configure --prefix=/opt/rieck
       ;;
   *)    
       echo "Unknown system or configuration"
       exit
       ;;
esac

if test $? -gt 0 ; then
   echo "Error: Configuration failed"
   exit 1
fi

read

# Compile
make clean 
make -j 4 
